20:
  /system/chassis/motherboard/gv100card0: &DEFAULTS
    entityInstance: 1
    entityID: 3
    interfaces:
      xyz.openbmc_project.Inventory.Item:
        PrettyName:
          IPMIFruProperty: Board Name
          IPMIFruSection: Board
21:
  /system/chassis/motherboard/gv100card1:
    <<: *DEFAULTS
    entityInstance: 2
22:
  /system/chassis/motherboard/gv100card2:
    <<: *DEFAULTS
    entityInstance: 3
23:
  /system/chassis/motherboard/gv100card3:
    <<: *DEFAULTS
    entityInstance: 4
24:
  /system/chassis/motherboard/gv100card4:
    <<: *DEFAULTS
    entityInstance: 5
25:
  /system/chassis/motherboard/gv100card5:
    <<: *DEFAULTS
    entityInstance: 6
