/xyz/openbmc_project/logging/send_event_logs_to_host:
    - Interface: xyz.openbmc_project.Object.Enable
      Properties:
          Enabled:
              Default: 'true'

/xyz/openbmc_project/dump/disable_system_dump:
    - Interface: xyz.openbmc_project.Object.Enable
      Properties:
          Enabled:
              Default: 'true'
