1:
  /system/chassis/motherboard/cpu0:
    entityID: 3
    entityInstance: 1
    interfaces:
      xyz.openbmc_project.Inventory.Decorator.Revision:
        Version:
          IPMIFruProperty: Custom Field 2
          IPMIFruSection: Board
          IPMIFruValueDelimiter: 58
      xyz.openbmc_project.Inventory.Decorator.Asset:
        BuildDate:
          IPMIFruProperty: Mfg Date
          IPMIFruSection: Board
        PartNumber:
          IPMIFruProperty: Part Number
          IPMIFruSection: Board
        Manufacturer:
          IPMIFruProperty: Manufacturer
          IPMIFruSection: Board
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Board
      xyz.openbmc_project.Inventory.Item:
        PrettyName:
          IPMIFruProperty: Name
          IPMIFruSection: Board
2:
  /system/chassis/motherboard/cpu1:
    entityID: 3
    entityInstance: 2
    interfaces:
      xyz.openbmc_project.Inventory.Decorator.Revision:
        Version:
          IPMIFruProperty: Custom Field 2
          IPMIFruSection: Board
          IPMIFruValueDelimiter: 58
      xyz.openbmc_project.Inventory.Decorator.Asset:
        BuildDate:
          IPMIFruProperty: Mfg Date
          IPMIFruSection: Board
        PartNumber:
          IPMIFruProperty: Part Number
          IPMIFruSection: Board
        Manufacturer:
          IPMIFruProperty: Manufacturer
          IPMIFruSection: Board
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Board
      xyz.openbmc_project.Inventory.Item:
        PrettyName:
          IPMIFruProperty: Name
          IPMIFruSection: Board
          Value: False
3:
  /system/chassis/motherboard:
    entityID: 7
    entityInstance: 1
    interfaces:
      xyz.openbmc_project.Inventory.Decorator.Asset:
        BuildDate:
          IPMIFruProperty: Mfg Date
          IPMIFruSection: Board
        PartNumber:
          IPMIFruProperty: Part Number
          IPMIFruSection: Board
        Manufacturer:
          IPMIFruProperty: Manufacturer
          IPMIFruSection: Board
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Board
      xyz.openbmc_project.Inventory.Item:
        PrettyName:
          IPMIFruProperty: Name
          IPMIFruSection: Board
  /system:
    entityID: 7
    entityInstance: 1
    interfaces:
      xyz.openbmc_project.Inventory.Decorator.Asset:
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Chassis
        Model:
          IPMIFruProperty: Part Number
          IPMIFruSection: Chassis


4:
  /system/chassis/motherboard/dimm0:
    entityID: 32
    entityInstance: 1
    interfaces:
      xyz.openbmc_project.Inventory.Item:
        PrettyName:
          IPMIFruProperty: Name
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Asset:
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Product
        Manufacturer:
          IPMIFruProperty: Manufacturer
          IPMIFruSection: Product
        PartNumber:
          IPMIFruProperty: Part Number
          IPMIFruSection: Product
        BuildDate:
          IPMIFruProperty: Mfg Date
          IPMIFruSection: Product
        Model:
          IPMIFruProperty: Model Number
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Revision:
        Version:
          IPMIFruProperty: Version
5:
  /system/chassis/motherboard/dimm1:
    entityID: 32
    entityInstance: 2
    interfaces:
      xyz.openbmc_project.Inventory.Item:
        PrettyName:
          IPMIFruProperty: Name
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Asset:
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Product
        Manufacturer:
          IPMIFruProperty: Manufacturer
          IPMIFruSection: Product
        PartNumber:
          IPMIFruProperty: Part Number
          IPMIFruSection: Product
        BuildDate:
          IPMIFruProperty: Mfg Date
          IPMIFruSection: Product
        Model:
          IPMIFruProperty: Model Number
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Revision:
        Version:
          IPMIFruProperty: Version
6:
  /system/chassis/motherboard/dimm2:
    entityID: 32
    entityInstance: 3
    interfaces:
      xyz.openbmc_project.Inventory.Item:
        PrettyName:
          IPMIFruProperty: Name
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Asset:
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Product
        Manufacturer:
          IPMIFruProperty: Manufacturer
          IPMIFruSection: Product
        PartNumber:
          IPMIFruProperty: Part Number
          IPMIFruSection: Product
        BuildDate:
          IPMIFruProperty: Mfg Date
          IPMIFruSection: Product
        Model:
          IPMIFruProperty: Model Number
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Revision:
        Version:
          IPMIFruProperty: Version
7:
  /system/chassis/motherboard/dimm3:
    entityID: 32
    entityInstance: 4
    interfaces:
      xyz.openbmc_project.Inventory.Item:
        PrettyName:
          IPMIFruProperty: Name
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Asset:
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Product
        Manufacturer:
          IPMIFruProperty: Manufacturer
          IPMIFruSection: Product
        PartNumber:
          IPMIFruProperty: Part Number
          IPMIFruSection: Product
        BuildDate:
          IPMIFruProperty: Mfg Date
          IPMIFruSection: Product
        Model:
          IPMIFruProperty: Model Number
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Revision:
        Version:
          IPMIFruProperty: Version
8:
  /system/chassis/motherboard/dimm4:
    entityID: 32
    entityInstance: 5
    interfaces:
      xyz.openbmc_project.Inventory.Item:
        PrettyName:
          IPMIFruProperty: Name
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Asset:
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Product
        Manufacturer:
          IPMIFruProperty: Manufacturer
          IPMIFruSection: Product
        PartNumber:
          IPMIFruProperty: Part Number
          IPMIFruSection: Product
        BuildDate:
          IPMIFruProperty: Mfg Date
          IPMIFruSection: Product
        Model:
          IPMIFruProperty: Model Number
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Revision:
        Version:
          IPMIFruProperty: Version
9:
  /system/chassis/motherboard/dimm5:
    entityID: 32
    entityInstance: 6
    interfaces:
      xyz.openbmc_project.Inventory.Item:
        PrettyName:
          IPMIFruProperty: Name
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Asset:
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Product
        Manufacturer:
          IPMIFruProperty: Manufacturer
          IPMIFruSection: Product
        PartNumber:
          IPMIFruProperty: Part Number
          IPMIFruSection: Product
        BuildDate:
          IPMIFruProperty: Mfg Date
          IPMIFruSection: Product
        Model:
          IPMIFruProperty: Model Number
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Revision:
        Version:
          IPMIFruProperty: Version
10:
  /system/chassis/motherboard/dimm6:
    entityID: 32
    entityInstance: 7
    interfaces:
      xyz.openbmc_project.Inventory.Item:
        PrettyName:
          IPMIFruProperty: Name
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Asset:
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Product
        Manufacturer:
          IPMIFruProperty: Manufacturer
          IPMIFruSection: Product
        PartNumber:
          IPMIFruProperty: Part Number
          IPMIFruSection: Product
        BuildDate:
          IPMIFruProperty: Mfg Date
          IPMIFruSection: Product
        Model:
          IPMIFruProperty: Model Number
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Revision:
        Version:
          IPMIFruProperty: Version
11:
  /system/chassis/motherboard/dimm7:
    entityID: 32
    entityInstance: 8
    interfaces:
      xyz.openbmc_project.Inventory.Item:
        PrettyName:
          IPMIFruProperty: Name
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Asset:
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Product
        Manufacturer:
          IPMIFruProperty: Manufacturer
          IPMIFruSection: Product
        PartNumber:
          IPMIFruProperty: Part Number
          IPMIFruSection: Product
        BuildDate:
          IPMIFruProperty: Mfg Date
          IPMIFruSection: Product
        Model:
          IPMIFruProperty: Model Number
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Revision:
        Version:
          IPMIFruProperty: Version
12:
  /system/chassis/motherboard/dimm8:
    entityID: 32
    entityInstance: 9
    interfaces:
      xyz.openbmc_project.Inventory.Item:
        PrettyName:
          IPMIFruProperty: Name
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Asset:
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Product
        Manufacturer:
          IPMIFruProperty: Manufacturer
          IPMIFruSection: Product
        PartNumber:
          IPMIFruProperty: Part Number
          IPMIFruSection: Product
        BuildDate:
          IPMIFruProperty: Mfg Date
          IPMIFruSection: Product
        Model:
          IPMIFruProperty: Model Number
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Revision:
        Version:
          IPMIFruProperty: Version
13:
  /system/chassis/motherboard/dimm9:
    entityID: 32
    entityInstance: 10
    interfaces:
      xyz.openbmc_project.Inventory.Item:
        PrettyName:
          IPMIFruProperty: Name
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Asset:
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Product
        Manufacturer:
          IPMIFruProperty: Manufacturer
          IPMIFruSection: Product
        PartNumber:
          IPMIFruProperty: Part Number
          IPMIFruSection: Product
        BuildDate:
          IPMIFruProperty: Mfg Date
          IPMIFruSection: Product
        Model:
          IPMIFruProperty: Model Number
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Revision:
        Version:
          IPMIFruProperty: Version
14:
  /system/chassis/motherboard/dimm10:
    entityID: 32
    entityInstance: 11
    interfaces:
      xyz.openbmc_project.Inventory.Item:
        PrettyName:
          IPMIFruProperty: Name
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Asset:
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Product
        Manufacturer:
          IPMIFruProperty: Manufacturer
          IPMIFruSection: Product
        PartNumber:
          IPMIFruProperty: Part Number
          IPMIFruSection: Product
        BuildDate:
          IPMIFruProperty: Mfg Date
          IPMIFruSection: Product
        Model:
          IPMIFruProperty: Model Number
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Revision:
        Version:
          IPMIFruProperty: Version
15:
  /system/chassis/motherboard/dimm11:
    entityID: 32
    entityInstance: 12
    interfaces:
      xyz.openbmc_project.Inventory.Item:
        PrettyName:
          IPMIFruProperty: Name
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Asset:
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Product
        Manufacturer:
          IPMIFruProperty: Manufacturer
          IPMIFruSection: Product
        PartNumber:
          IPMIFruProperty: Part Number
          IPMIFruSection: Product
        BuildDate:
          IPMIFruProperty: Mfg Date
          IPMIFruSection: Product
        Model:
          IPMIFruProperty: Model Number
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Revision:
        Version:
          IPMIFruProperty: Version
16:
  /system/chassis/motherboard/dimm12:
    entityID: 32
    entityInstance: 13
    interfaces:
      xyz.openbmc_project.Inventory.Item:
        PrettyName:
          IPMIFruProperty: Name
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Asset:
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Product
        Manufacturer:
          IPMIFruProperty: Manufacturer
          IPMIFruSection: Product
        PartNumber:
          IPMIFruProperty: Part Number
          IPMIFruSection: Product
        BuildDate:
          IPMIFruProperty: Mfg Date
          IPMIFruSection: Product
        Model:
          IPMIFruProperty: Model Number
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Revision:
        Version:
          IPMIFruProperty: Version
17:
  /system/chassis/motherboard/dimm13:
    entityID: 32
    entityInstance: 14
    interfaces:
      xyz.openbmc_project.Inventory.Item:
        PrettyName:
          IPMIFruProperty: Name
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Asset:
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Product
        Manufacturer:
          IPMIFruProperty: Manufacturer
          IPMIFruSection: Product
        PartNumber:
          IPMIFruProperty: Part Number
          IPMIFruSection: Product
        BuildDate:
          IPMIFruProperty: Mfg Date
          IPMIFruSection: Product
        Model:
          IPMIFruProperty: Model Number
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Revision:
        Version:
          IPMIFruProperty: Version
18:
  /system/chassis/motherboard/dimm14:
    entityID: 32
    entityInstance: 15
    interfaces:
      xyz.openbmc_project.Inventory.Item:
        PrettyName:
          IPMIFruProperty: Name
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Asset:
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Product
        Manufacturer:
          IPMIFruProperty: Manufacturer
          IPMIFruSection: Product
        PartNumber:
          IPMIFruProperty: Part Number
          IPMIFruSection: Product
        BuildDate:
          IPMIFruProperty: Mfg Date
          IPMIFruSection: Product
        Model:
          IPMIFruProperty: Model Number
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Revision:
        Version:
          IPMIFruProperty: Version
19:
  /system/chassis/motherboard/dimm15:
    entityID: 32
    entityInstance: 16
    interfaces:
      xyz.openbmc_project.Inventory.Item:
        PrettyName:
          IPMIFruProperty: Name
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Asset:
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Product
        Manufacturer:
          IPMIFruProperty: Manufacturer
          IPMIFruSection: Product
        PartNumber:
          IPMIFruProperty: Part Number
          IPMIFruSection: Product
        BuildDate:
          IPMIFruProperty: Mfg Date
          IPMIFruSection: Product
        Model:
          IPMIFruProperty: Model Number
          IPMIFruSection: Product
      xyz.openbmc_project.Inventory.Decorator.Revision:
        Version:
          IPMIFruProperty: Version
